### ISSUE TITLE
Do Activation no longer works.

### ISSUE THREAD

**Issue by Petro31** [zaluthar/zaluthar.github.io#1]
This flasher no longer works with the CDGK2s.  I have 4, all 4 fail at the same position.  After connecting, "Do Activation" sends out the following:
```
Send: a2000000
Enc_19: 000000000100
Send: 00000101
Enc_19: 010001000000
Send: 00000100
Send: 15000000
Send: 000000030400
```

Then it sits forever.  Nothing else occurs.  The connection to the device remains but "Do Activation" does nothing.

**Comment by Darrelde** [comment]
I recently purchased 4 CGPR1 motion sensors and encountered this issue while attempting to activate them for use with esphome.

After considerable fumbling around I stumbled on to a workaround and have successfully activated the 4 devices.  Here's what worked for me:

1.  I added the device to the IOS Qingping+ app.
2.  On my PC chrome browser.  From Zaluthers' modified Telink Flasher webpage click on the "Connect" button to search for available devices.  Since the device is paired to the Qingping app it won't be found by the flasher.
3. Leaving the flasher connect window  active in the browser go to the Qingping app and delete the device from the app.
4. On the flasher window click the "Rescan" link.  The device should now be found.  Click the "Pair" link,  It should now connect.
5.  Once connected click on the "Do Activation" link.  It should now successfully activate and generate a bind key for use in esphome.
